### PR TITLE
feat(scss): add modern css grid support to legacy column classnames

### PR DESCRIPTION
**Pull request by seejamescode**
This update adds modern css grid support to legacy column classnames for easier transition from flexbox.

Action required to end users of your CSS Gridish grid would be that they are about to have all width behaviors attached to legacy classes also take affect in modern browsers. This means they would need to eliminate their excess CSS Grid code or make sure to overwrite the rules they did not mean to transfer over from legacy.

We are in a weird place by using semver for a build tool. This has no breaking changes for the grid-creating users of Gridish, but is a breaking change to our users’ users.

Thanks to @nilesh-chavan for starting this initiative.

### CODE REVIEW

**Comment by nilesh-chavan** [comment]
can we make complex CSS grid using css-gridish? because grid class create 100vw width flexbox. that's why we can't use a nested grid. am I right?

**Comment by seejamescode** [comment]
Hey @nilesh-chavan, the current version of Gridish already supports nested grids. You can also try all of the new work with the v2.0.0 beta: https://github.com/IBM/css-gridish/tree/v2.0.0

**Comment by bjfresh** [comment]
Maybe I'm overlooking something, but I've scoured the repo and can't really see how Gridish deals with grid-column shorthands that define the initial column offset in legacy. Within a container having 12 cols, I'm finding that I can set element width successfully using the legacy classes like so:

yourPrefix-grid__col--md--8

while applying:

grid-column: 3/span 8;

Is there a recommended method for shifting the element over to the 3rd column?

Thanks.

(I'm currently on 1.0.7, btw)

**Comment by seejamescode** [comment]
Hey @bjfresh, that is an honest limitation of these classes.

The classes work like traditional float and flexbox grids where all of the items have to ”push” each other over. The hope is that these classes help a dev team transition from their existing float and flexbox grid use to CSS Grid. Then they can start applying smarter CSS Grid rules like `grid-column: 3 / span 8;`.

In [v2.0.0](https://github.com/IBM/css-gridish/tree/v2.0.0), this way of doing things does not change. Though we do add the CSS Grid code for the `col` classes.

**Pull request closed without merging**
